Raise a custom exception when calling a valid service method that is not implemented by a specific provider (instead of raising the usual Ruby NoSuchMethodError)